sudo: false

language: java

env:
  global:
    - PROTOBUF_VERSION=3.0.0-beta-1
    - OPENSSL_VERSION=1.0.2d
    - LDFLAGS=-L/tmp/protobuf-${PROTOBUF_VERSION}/lib
    - CXXFLAGS=-I/tmp/protobuf-${PROTOBUF_VERSION}/include
    - LD_LIBRARY_PATH=/tmp/protobuf-${PROTOBUF_VERSION}/lib:/tmp/openssl-${OPENSSL_VERSION}/lib

before_install:
  - buildscripts/make_dependencies.sh # build protoc into /tmp/protobuf-${PROTOBUF_VERSION}
  - mkdir -p $HOME/.gradle
  - echo "checkstyle.ignoreFailures=false" >> $HOME/.gradle/gradle.properties

before_script:
  - test -z "$(git status --porcelain)" || (git status && echo Error Working directory is not clean. Forget to commit generated files? && false)

after_success:
  - ./gradlew :grpc-all:coveralls

#jdk:
#  - oraclejdk8

os:
  #- linux
  - osx

notifications:
  email: false

cache:
  directories:
    - /tmp/protobuf-${PROTOBUF_VERSION}
    - $HOME/.m2/repository/io/netty
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper

before_cache:
  - rm $HOME/.gradle/caches/modules-2/modules-2.lock
  - find $HOME/.gradle/wrapper -not -name "*-all.zip" -and -not -name "*-bin.zip" -delete
